# Generated by Django 4.2.6 on 2023-11-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadAppInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carat', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GoodAppInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carat', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
    ]
